package si.fri.prpo.soap.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import si.fri.prpo.sheme.izdelki.sporocila.v1.VrniIzdelekRequest;
import si.fri.prpo.sheme.izdelki.sporocila.v1.VrniIzdelekResponse;
import si.fri.prpo.sheme.izdelki.sporocila.v1.VrniIzdelkeRequest;
import si.fri.prpo.sheme.izdelki.sporocila.v1.VrniIzdelkeResponse;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-01-08T19:34:57.220+01:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://prpo.fri.si/storitve/izdelki/v1", name = "IzdelkiPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IzdelkiPort {

    @WebMethod(action = "http://prpo.fri.si/storitve/izdelki/v1")
    @WebResult(name = "vrniIzdelkeResponse", targetNamespace = "http://prpo.fri.si/storitve/izdelki/v1", partName = "parameters")
    public VrniIzdelkeResponse vrniIzdelke(
        @WebParam(partName = "parameters", name = "vrniIzdelkeRequest", targetNamespace = "http://prpo.fri.si/storitve/izdelki/v1")
        VrniIzdelkeRequest parameters
    );

    @WebMethod(action = "http://prpo.fri.si/storitve/izdelki/v1")
    @WebResult(name = "vrniIzdelekResponse", targetNamespace = "http://prpo.fri.si/storitve/izdelki/v1", partName = "parameters")
    public VrniIzdelekResponse vrniIzdelek(
        @WebParam(partName = "parameters", name = "vrniIzdelekRequest", targetNamespace = "http://prpo.fri.si/storitve/izdelki/v1")
        VrniIzdelekRequest parameters
    );
}
